refs #14: implement FindFirstElementGreaterOrEqualToKey
huandu/skiplist pull request #15
Opened 2021-09-22 13:02 UTC by someblue

2021-09-23 04:24 UTC, huandu requested changes
感谢快速提供了一个 PR，我提了几个代码设计和风格的建议，辛苦修改下，欢迎在 issue 里面讨论。

2021-09-23 04:24 UTC, huandu commented on skiplist.go
> +func (list *SkipList) FindFirstElementGreaterOrEqualToKey(key interface{}) (elem *Element) {
这个接口的名字太长了，希望改成 Find，注释里写好这个函数的功能即可，不用那么长的名字。

2021-09-23 04:24 UTC, huandu commented on skiplist.go
> +		elem = nil
没必要额外给 elem = nil，默认值就是 nil。

2021-09-23 04:24 UTC, huandu commented on skiplist.go
> +		elem = nil
同上，不需要赋值。

2021-09-23 04:24 UTC, huandu commented on skiplist.go
> +	firstElem := list.FindFirstElementGreaterOrEqualToKey(key)
由于 Find 函数里面调用 calcScore 计算了 score，下面的代码再次计算了一次，有些浪费，建议写一个内部函数 `findNext(start *Element, score float64, key interface{}) (elem *Element)`，传入计算好的 score，省去额外的 calcScore。

2021-09-23 04:24 UTC, huandu commented on skiplist.go
> +func (list *SkipList) FindFirstElementGreaterOrEqualToKey(key interface{}) (elem *Element) {
另外建议提供两个公开方法：

```go
// 相当于调用 list.FindNext(nil, key)
func (list *SkipList) Find(key interface{}) (elem *Element)

// 从 elem 开始查找下一个符合要求的 key，elem 自身不包含。
func (list *SkipList) FindNext(elem *Element, key interface{}) (elem *Element)
```

另外提供一个私有方法，将计算好的 score 放进去，减少 calcScore 调用。

```go
func (list *SkipList) findNext(start *Element, score float64, key interface{}) (elem *Element)
```

2021-09-23 13:57 UTC, someblue commented
@huandu hello，感谢 comments，已根据 comments 更新了

2021-09-23 14:57 UTC, someblue commented
@huandu hello 感谢 comments，已调整代码

2021-09-24 02:38 UTC, merged

2021-09-24 02:38 UTC, huandu commented
没有问题了，已经合并。